---
title: "three"
author: "Aghasi Tavadyan"
date: "2023-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r}
scale_factor = 15

colors_three = c("#A8D185", "#04905E", "#9acd32",
                 "#3D9618", "#8AD378", "#3FD485", "#089E79",
                 "#079094", "#2F9B61", "#50C878", "#008000", "#008000")

# colors_three = as.character(paletteer::paletteer_d("ggsci::light_green_material"))

bauble_colours = c("#e5d08f", "#e3d4b6",
                   "#cacbce", "#9c9c9c", "#e1dfdf",
                   "#c94c4c", "#8d1414")

bauble_colours = c(
"#646F75", "#949399", "#8C9EAA", "#C3C4C6", "#9CC6D4", "#7FA490", "#CD936D", "#DB7076", "#E04C52")


 reds <- c("#ff0000", "#ffa07a", "#f08080", "#fa8072", "#e9967a",
    "#ff6347", "#cd5c5c", "#ff4500", "#dc143c", "#b22222")

bubbles <- 
  crossing(
    x = 1:(scale_factor*2),
    y = 1:scale_factor
  ) |> 
  filter(
    x %% 2 != y %% 2,
    y <= x,
    y <= -x + max(x)
  ) %>%
  mutate(
    x = x / 2,
    shp = sample(1:7, nrow(.), replace = T),
    sz = sample(seq(.5,1,by=.1), nrow(.), replace = T),
    col1 = sample(bauble_colours, nrow(.), replace = T),
  )

main_tree <- 
  crossing(
  x = 1:(scale_factor*2),
  y = 1:scale_factor,
  x_prime = seq(-1, 1 , 0.01)
) |> 
  filter(
    x %% 2 != y %% 2,
    y <= x,
    y <= -x + max(x)
  ) %>%
  mutate(
      col1 = sample(colors_three, nrow(.), replace = TRUE)
  ) %>% 
  bind_rows(
    tibble(
      x = scale_factor, 
      y = scale_factor + 1,   
      x_prime = seq(-1, 1 , 0.01),
      col1 = "red"
    )
  ) %>% 
  mutate(
    y_prime = sqrt(1 - x_prime^2),
    y_prime2 = ifelse(x_prime >= 0, x_prime - 1, x_prime + 1),
    y_prime2 = sqrt(1 - (y_prime2)^2)-1,
    x_prime = x_prime + x,
    y_prime = y_prime + y,
    y_prime2 = y_prime2 + y,
    x_prime = x_prime / 2,
    x = x / 2,
    # nrow = nrow(x = _),
  ) |> 
  pivot_longer(contains("y_prime"), values_to = "y_prime") |> 
  filter(y_prime >= 1)








gerlyanda <-
  function(len = 30, resalution = 500) {
    j = NULL
    j[1] = 0
    
    for (i in 1:len) {
      # j[i + 1] = cumsum(j)
      if ((i + sum(j)) %% 2 == 0) {
        j[i + 1] = sample(c(0, 1), size = 1)
      } else{
        j[i + 1] = sample(c(0, -1), size = 1) 
      }
    }
    
    j = tail(j, -1)
    
    data <- 
      tibble(
        x_floor = 1:len,
        y_floor = cumsum(j)
      ) |> 
      crossing(x = seq(0, 1 - 1/resalution, 1/resalution)) |> 
      mutate(
        x = x_floor + x,
        y = case_when(
          (x_floor + y_floor) %% 2 == 0 ~ sqrt(1 - (x %% x_floor)^2),
          (x_floor + y_floor) %% 2 == 1 ~ sqrt(1 - (x %% x_floor - 1)^2),
        ),
        y = y + y_floor
      ) |> 
      select(x,y)
    
    return(data)
  }



gerlyanda_multiplayer <- function(count = 7) {
  
  data <- NULL
  
  for (i in 1:count) {
    data <- 
      gerlyanda(resalution = 70) |> 
      mutate(
        group = paste0("count", i), 
        hight = sample(seq(1, 19, 2), 1),
        color = sample(reds, 1)
      ) |> 
      bind_rows(data)
  }
  
  data |> 
    arrange(group) |> 
    mutate(
      y = y + hight
    ) |> 
    filter(
      y >= 1,
      floor(y) <= floor(x),
      floor(y) <= -floor(x) + max(x) - 1
    ) |> 
    mutate(x = x /2)
}


gerlyanda_multiplayer <-
  function() {
  
    gerlyanda(resalution = 70) |> 
      crossing(
        nesting(
          linetype = paste0("count", 1:8), 
          color = sample(reds, 8)
        ),
        nesting(
          hight = seq(-5, 33, 2),
        )
      ) |> 
      arrange(hight) |> 
      mutate(
        y = y + hight
      ) |> 
      filter(
        y >= 1,
        floor(y) <= floor(x),
        floor(y) <= -floor(x) + max(x) - 1
      ) |> 
      mutate(x = x /2)
  }


gerlyanda_multiplayer()

snow <- 
  tibble(
    x = sample(seq(1, max(cone$x)+1, by=.01), 100, replace = F),
    y = sample(seq(1, max(cone$y)+1, by=.01), 100, replace = F)
  ) %>% 
  group_by(x) %>% 
  nest() %>% 
  mutate(
    data =  map(
      data, 
      ~data.frame(
        y=seq(.$y, .$y-sample(seq(.5,1,by=.01),1), length.out = 100)
      ) %>% 
        mutate(time = sample(seq(0.5,.9, .01), 1)) %>% 
        mutate(time = seq(unique(time), unique(time)+.02, length.out = nrow(.)))
    )
  ) %>% 
  unnest() 



library(gganimate)
library(transformr)



main_tree |> 
  ggplot(aes(x_prime, y_prime, group = paste(x, y))) +
  geom_tile(aes(x = scale_factor/2, y = 0, width = 2, height = 2), fill = "brown4") +
  geom_path() +
  geom_polygon(aes(fill = I(col1), color = I(col1))) +
  geom_line(
    data = gerlyanda_multiplayer(),
    aes(x, y, linetype = as.factor(linetype), group = hight, color = I(color)),
    size = 1.8
  ) +
  geom_point(
    data = bubbles, 
    aes(x = x, y = y + 0.4, shape = factor(shp), size=sz, color = I(col1)), 
    show.legend = F
  ) +
  # geom_jitter(data=snow, aes(x,y,group=x), colour="white", shape=8, size=1) +
  scale_shape_manual(values = c(20:25,8)) +
  theme_void() + 
  coord_fixed() +
  theme(
    plot.background = element_rect(fill="#0E4732"), 
    title = element_text(colour="white"),
    legend.position = "drop"
  ) +
  labs(
    caption = "tvyal.com"
  ) +
  transition_states(linetype, transition_length = 2, state_length = 1) +
  # transition_states(color, transition_length = 2, state_length = 1) + 
  enter_fade() +
  exit_fade()


  transition_time(time) + 
  ease_aes('sine-in-out')
    
  




 



# crossing(
#   x = seq(-1, 1, 0.01),
#   y = seq(-1, 1, 0.01)
# ) |> 
#   filter(
#     x^2 + y^2 < 1,
#     asin(y) < pi / 4 & acos(x) > pi / 3
#     ) %>%
#   mutate(
#     x = x / 2.5,
#     shp = sample(1:7, nrow(.), replace = T),
#     sz = sample(seq(.5,1,by=.1), nrow(.), replace = T),
#     col1 = sample(bauble_colours, nrow(.), replace = T),
#   ) |> 
#   na.omit() |> 
#   ggplot() +
#   geom_point(
#     aes(x = x, y = y + 0.4, shape = factor(shp), size=sz, color = I(col1)), 
#     show.legend = F
#   )
# 
# # tibble()
# seq(0, 2*pi, length = 6)


```

